# Generated by Django 3.1.4 on 2021-01-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_remove_videoitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoitem',
            name='category',
            field=models.CharField(choices=[(0, 'Música'), (1, 'Cine'), (2, 'Animales'), (3, 'Ciencia'), (3, 'Otros')], default=0, max_length=32),
        ),
    ]
