# Generated by Django 3.1.4 on 2021-01-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_videoitem_image_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoitem',
            name='image_preview',
            field=models.ImageField(default=None, upload_to='video_collection/uploads/'),
        ),
    ]
