# Generated by Django 3.1.4 on 2021-01-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_auto_20210116_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoitem',
            name='image_preview',
            field=models.ImageField(default='', upload_to='uploaded'),
        ),
    ]
