# Generated by Django 3.1.4 on 2021-01-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0008_auto_20210117_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoitem',
            name='image_preview',
            field=models.ImageField(default='', upload_to='video_collection/uploaded'),
        ),
    ]
